package crawler;

import java.io.*;
import javax.swing.*;

public class PantallaPrincipal extends javax.swing.JFrame {

    
    /*================== Variables Locales ================*/
    
    private Cola urls, urlsaux;
    private String Directorio;
    static final int  UrlsMax = 30;
    
    public PantallaPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        OcultarDePantalla();
    }
    
    
    /*=========== Funcion Para Ocultar Paneles Componentes De la GUI =============*/
    public void OcultarDePantalla(){
        ScrollListaUrl1.setVisible(false);
        ScrollListaPaginas.setVisible(false);
        BotonListarReferencias.setVisible(false);
        BotonObtenerUrl.setVisible(false);
        TextRaiz.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextRaiz = new javax.swing.JTextField();
        TextoCrawler = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Matricula = new javax.swing.JLabel();
        TextoRaiz = new javax.swing.JLabel();
        BotonSelCarpeta = new javax.swing.JButton();
        BotonObtenerUrl = new javax.swing.JButton();
        BotonListarReferencias = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        ScrollListaPaginas = new javax.swing.JScrollPane();
        ListaPaginas = new javax.swing.JList<>();
        ScrollListaUrl1 = new javax.swing.JScrollPane();
        ListaUrl1 = new javax.swing.JList<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextRaiz.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(TextRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 390, 30));

        TextoCrawler.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        TextoCrawler.setForeground(new java.awt.Color(51, 51, 51));
        TextoCrawler.setText("Proyecto Crawler");
        getContentPane().add(TextoCrawler, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        Nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setText("Alejandro Hernández Paredes");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        Matricula.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Matricula.setForeground(new java.awt.Color(51, 51, 51));
        Matricula.setText("201740063");
        getContentPane().add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, 30));

        TextoRaiz.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        TextoRaiz.setForeground(new java.awt.Color(51, 51, 51));
        TextoRaiz.setText("Raíz: ");
        getContentPane().add(TextoRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        BotonSelCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Folder_34x10_1.jpg"))); // NOI18N
        BotonSelCarpeta.setBorder(null);
        BotonSelCarpeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSelCarpeta.setMaximumSize(new java.awt.Dimension(85, 43));
        BotonSelCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSelCarpetaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSelCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 96, 50, 40));

        BotonObtenerUrl.setBackground(java.awt.SystemColor.activeCaptionBorder);
        BotonObtenerUrl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonObtenerUrl.setForeground(new java.awt.Color(51, 51, 51));
        BotonObtenerUrl.setText("Obtener URL's");
        BotonObtenerUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonObtenerUrlActionPerformed(evt);
            }
        });
        getContentPane().add(BotonObtenerUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 40));

        BotonListarReferencias.setBackground(java.awt.SystemColor.activeCaptionBorder);
        BotonListarReferencias.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonListarReferencias.setForeground(new java.awt.Color(51, 51, 51));
        BotonListarReferencias.setText("Listar Referencias");
        BotonListarReferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarReferenciasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonListarReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, 40));

        BotonLimpiar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        BotonLimpiar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, -1, -1));

        BotonSalir.setBackground(java.awt.SystemColor.activeCaptionBorder);
        BotonSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(51, 51, 51));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 650, -1, -1));

        ScrollListaPaginas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        ListaPaginas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ScrollListaPaginas.setViewportView(ListaPaginas);

        getContentPane().add(ScrollListaPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 470, 380));

        ScrollListaUrl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        ListaUrl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ScrollListaUrl1.setViewportView(ListaUrl1);

        getContentPane().add(ScrollListaUrl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 80, 370));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_Gris.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /*======================= Boton Seleccion Carpeta =========================*/
    private void BotonSelCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSelCarpetaActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES); //Asigancion Solo Apertura De Directorios 
        
        int Seleccion = fc.showOpenDialog(TextoRaiz);
        
        if(Seleccion == JFileChooser.APPROVE_OPTION){
            TextRaiz.setText(fc.getSelectedFile().getAbsolutePath());
            Directorio = TextRaiz.getText();
            BotonObtenerUrl.setVisible(true);
        }
        
    }//GEN-LAST:event_BotonSelCarpetaActionPerformed

    
    
    /*=================== Boton Busqueda Paginas HTML ==================*/
    private void BotonObtenerUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonObtenerUrlActionPerformed
        
        if(TextRaiz.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Debes Seleccionar una Capeta \nPara Poder Buscar Archivos HTML");
        }else{
            File dir = new File(TextRaiz.getText());
            
            String Ficheros[] = dir.list();
            
            if(Ficheros.length == 0){
                JOptionPane.showMessageDialog(rootPane,"No Existen Archivos En La Carpeta Seleccionada");
            }else{
                urls = new Cola();
                int i=0;
                
                while(i < Ficheros.length){
                    if(Ficheros[i].contains("html")){
                        if(!urls.verificar_Repetido(Ficheros[i])){
                            urls.push(Ficheros[i]);
                        }
                    }
                    i++;
                }
                
                urlsaux = urls;
                DefaultListModel modelo = new DefaultListModel();   
                
                int tam = urlsaux.getSize();
                
                for(i=1;i<=tam;i++){
                    String Taux = ("URL"+i);
                    modelo.addElement(Taux);
                }
                
                ListaUrl1.setModel(modelo);
                ScrollListaUrl1.setVisible(true);
            }
            
            BotonListarReferencias.setVisible(true);
        }
        
    }//GEN-LAST:event_BotonObtenerUrlActionPerformed
    
    
    /*======================= Boton Obtener Paginas ===========================P*/
    private void BotonListarReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarReferenciasActionPerformed
        File archivo = null;
        FileReader fr = null;
        BufferedReader br;
        
        try{
            
            JOptionPane.showMessageDialog(rootPane,"Estado Actual  De La Cola\n======================================\n" + urls.toString());
            urlsaux = urls;
            int n = urls.getSize(), i = 0;
            DefaultListModel modelo2 = new DefaultListModel();
            
            while(i < n){
                
                JOptionPane.showMessageDialog(null,"Iniciando obtencion Referencias URL"+(i+1));
                
                String direc = Directorio + "\\"+ urls.pop();
                
                System.out.println("Abriendo Archivo: "+direc);
                
                archivo = new File (direc);

                fr = new FileReader (archivo);
                br = new BufferedReader(fr);

                String linea;
                int r=0;
                
                while((linea=br.readLine())!=null){
                    
                    if(linea.contains("href")){
                        int b=0,j=0;
                        r++;

                        String ref = "";

                        while(b!=2){
                            if(linea.charAt(j) == '\"' ){ //Busqueda de Comillas para Delimitar inicio y fin del ref
                                b++;
                            }

                            if(b<2 && b>0){
                                ref = ref + linea.charAt(j);
                            }

                            j++;
                        }

                        ref = ref + "\"";

                        if(!urls.colallena()){
                            if(!urls.verificar_Repetido(ref)){
                                urls.push(ref);
                            }
                        }
                    }
                }
                
                if(r==0){
                    JOptionPane.showMessageDialog(rootPane,"No Se Encontraron Referencias En el Archivo "+archivo.getName());
                }else if(r>0){
                    JOptionPane.showMessageDialog(rootPane,"Se Encontraron "+r+" Referencias En el Archivo "+archivo.getName());
                }
                
                JOptionPane.showMessageDialog(rootPane,"Estado Actual  De La Cola\n======================================\n" + urls.toString());
                i++;
            
            }
            
            
            
            int tam = this.urlsaux.getSize();
            int k=0;
                
            while(k<=tam){
                String Taux = this.urlsaux.pop();
                modelo2.addElement(Taux);
                k++;
            }                
            
            ListaPaginas.setModel(modelo2);
            ScrollListaPaginas.setVisible(true);
            
            BotonListarReferencias.setVisible(false);
            
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_BotonListarReferenciasActionPerformed
    
    /*================= Boton Limpiar ====================*/
    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        OcultarDePantalla();
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonListarReferencias;
    private javax.swing.JButton BotonObtenerUrl;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSelCarpeta;
    private javax.swing.JLabel Fondo;
    private javax.swing.JList<String> ListaPaginas;
    private javax.swing.JList<String> ListaUrl1;
    private javax.swing.JLabel Matricula;
    private javax.swing.JLabel Nombre;
    private javax.swing.JScrollPane ScrollListaPaginas;
    private javax.swing.JScrollPane ScrollListaUrl1;
    private javax.swing.JTextField TextRaiz;
    private javax.swing.JLabel TextoCrawler;
    private javax.swing.JLabel TextoRaiz;
    // End of variables declaration//GEN-END:variables
}
